[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tourchain_reputation = "2GWdm3guUBQBLdA3VB9ECAwzN6UdpEMgs2VrKHiKfBXy"
tourchain_escrow = "11111111111111111111111111111111"
tourchain_proof = "11111111111111111111111111111111"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
