[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contracts = "2GWdm3guUBQBLdA3VB9ECAwzN6UdpEMgs2VrKHiKfBXy"

[provider]
cluster = "devnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "cargo test"

[hooks]
